# Generated by Django 3.0.6 on 2020-05-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=64)),
                ('qualification', models.CharField(max_length=32)),
                ('skills', models.CharField(max_length=256)),
                ('experience', models.CharField(max_length=2)),
                ('resume', models.FileField(upload_to='resume')),
            ],
        ),
    ]
